config/routes.rb
Rails.application.routes.draw do
  root 'bios#index'
  resources :bios
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  has_many :photos
  validates :life, presence: true, length: { minimum: 8  }
  validates :person, presence: true, length: { minimum: 8 }
  validates :dob, presence: true, length: { minimum: 8 }
  validates :hobbies, presence: true, length: { minimum: 8 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :bios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  def index
    @bio = Bio.order("RANDOM()").first
  end

  def create
    @bio = Bio.create(bio_params)
    if @bio.invalid?
      flash[:error] = '<strong> Could not save</strong> the data you entered is invalid'
    end
    redirect_to root_path
  end

  private

  def bio_params
    params.require(:bio).permit(:person, :life, :dob, :hobbies)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/views/bios/index.html.erb
<h2>
  <span> BIO / No. <%= @bio.id%></span>
  Here is your <u>Random Bio!</u> Broaden your horizons by meeting new People!
</h2>

<h1><%= @bio.person %></h1>
<h2><%= @bio.life %></h2>
<h2>Individual's hobbies: <%= @bio.hobbies%></h2>
<h2>Individuals Birthday: <%= @bio.dob %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/bios/new.html.erb
<h1>Enter The Bio Infomation</h1>
<%= simple_form_for @bio do |f| %>
  <%= f.input :person %>
  <%= f.input :life %>
  <%= f.input :dob %>
  <%= f.input :hobbies %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dhh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path do %>
          <div class="circle">
            <br />
            Add 
            <br />
            Interesting
            <br /> 
            People
          </div>
        <% end %>
      </div>
      <div class="col col-sm-4 hidden-xs-down slogan">
        Make a quick bio!
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
        <%= link_to 'Add New Bios', new_bio_path, data: {toggle: 'modal', target: '#myModal'} %>
      </div>
    </header>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Add Your Favorite Bio</h4>
          </div>
          <%= simple_form_for Bio.new do |f| %>
            <div class="modal-body">
              <%= f.input :person, label: "Who do you want to add?", placeholder: "David Heinemeier Hannsson" %>
              <br />
              <%= f.input :life, label: "What is his/her story?", placeholder: "He is a Danish programer who created Ruby on Rails." %>
              <br />
              <%= f.input :dob, label: "When was he/she born?", placeholder: "October 15,1979" %>
              <br />
              <%= f.input :hobbies, label: "what do they like to do in their spare time?", placeholder: "race car driving and photography" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit 'Create', class: 'btn btn-danger' %>
          </div>   
          <% end %>
        </div>
      </div>
    </div>


    <hr />


    <br class="clear" />
  <div class="container">
    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "More Bio? Click Me!", root_path, class: 'next-qsuote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Created in Houston,TX by Kevin Nguyen <br /> Need to get in touch? <a href="mailto:kev.ftw595@gmail.com">Email Me</a>
          </div>
        </div>
      </div>
    </div>



  </body>
</html>